project:
  ticket-number: CUR-001

curator:
  name: Ken Lui
  email: kenlh.lui@utoronto.ca
  institution:
    name: University of Toronto
    department: Map & Data Library

submission:
  dataset:
    title: Dataset Title
  submitter:
    name: First_Name Last_Name
    email: example@utoronto.ca
  date: 2024-01-01
