services:
  data-curation-tool:
    build: .
    image: data-curation-tool:latest
    container_name: data-curation-tool
    ports:
      - "9005:80"
    env_file:
      - ./.env   # Your .env file
    volumes:
      - ./new_dir:/workdir
    restart: unless-stopped
